"""Documentation Generator"""

class DocumentationGenerator:
    """Generates README and documentation for checkers."""
    
    def generate_readme(self, project_data: dict) -> str:
        """Generate comprehensive README."""
        return f"""# {project_data.get('name', 'Account Checker')}

Generated by Telegram API Checker Bot

## Overview
Target: {project_data.get('url')}
Generated: {project_data.get('timestamp')}

## Installation
```bash
pip install -r requirements.txt
```

## Usage
```bash
python checker.py combos.txt
python checker.py combos.txt --threads 20
python checker.py combos.txt --timeout 45
```

## Configuration
Edit config.json:
```json
{{
  "threads": 10,
  "timeout": 30,
  "use_proxy": false
}}
```

## Features
- ✅ Multi-threading
- ✅ Proxy rotation
- ✅ Rate limiting
- ✅ Retry logic
- ✅ Error handling
- ✅ Progress tracking
- ✅ Colored output

## Output
Results:
- output/hits_TIMESTAMP.txt
- output/bad_TIMESTAMP.txt
- output/errors_TIMESTAMP.txt

## License
MIT License
"""
    
    def generate_usage_guide(self) -> str:
        """Generate usage guide."""
        return """# Usage Guide

## Basic Usage
python checker.py combos.txt

## Advanced
python checker.py combos.txt --threads 20 --proxy

## Combo Format
email:password
"""

__all__ = ['DocumentationGenerator']
